<table border=1 class="table table-striped table-hover table-bordered">
    <tr>
        <th>Id</th>
        <th>Type</th>
        <th>Brand</th>
        <th>Model</th>
        <th>Serial No.</th>
        <th>Warranty</th>
        <th>Asset Tag</th>
        <th>Description</th>
    </tr>
    $ASSETS:{
    <tr>
        <td>$attr.id$</td>
        <td>$attr.type$</td>
        <td>$attr.brand$</td>
        <td>$attr.model$</td>
        <td>$attr.serialNo$</td>
        <td>$attr.warranty$</td>
        <td>$attr.assetTag$</td>
        <td>$attr.description$</td>
    </tr>
    }$
</table>