<div class="span1"></div>
<div class="span10">
    <div class="row-fluid">
        <div class="page-title">
            <h1>Asset Management System</h1>
        </div>
    </div>
    <div class="row-fluid">
        <ul class="nav-tabs">
            <li><a href="/" id="create">New</a></li>
            <li><a href="/show" id="Stock">Stock</a></li>
            <li><a href="/types" id="types">Add Asset Type</a></li>
        </ul>
    </div>
</div>