<html>
<head>
    <title> Assets </title>
    <link rel="stylesheet" type="text/css" href="resources/css/main.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="resources/css/bootstrap.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="resources/css/jquery.css" media="screen">
    <script type="text/javascript" src="resources/js/jquery.js"></script>
    <script type="text/javascript" src="resources/js/bootstrap.js"></script>
    <script type="text/javascript" src="resources/js/jquery-ui.js"></script>
    <script type="text/javascript" src="resources/js/new.js"></script>
</head>
<body>
    <div class="header">$partial/header()$</div>
    <div class="content">
        <div class="center-alignment">
          <div class="pageContainer">$body$</div>
        </div>
    </div>
    <div class="footer">
        <div class="center-alignment">$partial/footer()$</div>
    </div>
</body>
</html>