<html>
<head>
    <title> Assets </title>
    <link rel="stylesheet" type="text/css" href="resources/css/bootstrap.css" media="screen"/>
    <script type="text/javascript" src="resources/js/jquery.js"></script>
    <script type="text/javascript" src="resources/js/new.js"></script>
</head>
<body>
<div class="row-fluid">$partial/header()$</div>
<div class="row-fluid pageContainer">$body$</div>
<div class="row-fluid">$partial/footer()$</div>
</body>
</html>