<html>
<head>
    <title> Assets </title>
    <link rel="stylesheet" type="text/css" href="resources/css/main.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="resources/css/bootstrap.css" media="screen"/>
    <script type="text/javascript" src="resources/js/jquery.js"></script>
    <script type="text/javascript" src="resources/js/bootstrap.js"></script>
    <script type="text/javascript" src="resources/js/new.js"></script>
</head>
<body>
<div class="navbar-background"></div>
<div class="center-alignment">
    <div class="header">$partial/header()$</div>
    <div class="content">
        <div class="pageContainer">$body$</div>
    </div>
    <div class="footer">$partial/footer()$</div>
</div>
</body>
</html>